

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  create-file-and-read-it:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Create the file"
          command: "echo \"The Date: $(date)\" > some_file.txt"
      - run:
          name: "Read the file"
          command: "cat some_file.txt"
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: us-east-1
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: some_file.txt
          to: 's3://roman-test-bucket'
      

workflows:
  create-file-and-read-it-workflow:
    jobs:
      - create-file-and-read-it:
          context:
              - s3-bucket